#!/usr/bin/env python3
"""Self-host the four Google font families telemetry.css actually uses.

Fetches the latin subset only (the site is lang="en"; the latin range already
covers em-dashes and curly quotes), downloads each woff2 into the theme, and
emits a fonts.css with local src paths. Idempotent.
"""
import os
import re
import sys
import urllib.request

THEME = "/Users/jonhdoe/Repository/scryops-site/themes/scryops"
FONT_DIR = os.path.join(THEME, "static/fonts/vendor")
CSS_OUT = os.path.join(THEME, "assets/css/fonts.css")

# Exactly the families/weights from head.html's Google URL.
GOOGLE_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=IBM+Plex+Mono:wght@400;500;600"
    "&family=Courier+Prime:wght@400;700"
    "&family=Space+Mono:wght@400;700"
    "&family=Press+Start+2P"
    "&display=swap"
)
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
      "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = fetch(GOOGLE_URL)

    # Split into "/* subset */ @font-face {...}" units, keep latin only.
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    # blocks = ['', subset1, body1, subset2, body2, ...]
    out_rules = []
    downloaded = {}
    for i in range(1, len(blocks), 2):
        subset = blocks[i]
        body = blocks[i + 1]
        if subset != "latin":
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        url = re.search(r"src:\s*url\(([^)]+)\)", body).group(1)
        fname = f"{slug(fam)}-{weight}.woff2"
        dest = os.path.join(FONT_DIR, fname)
        if fname not in downloaded:
            blob = fetch(url, binary=True)
            with open(dest, "wb") as f:
                f.write(blob)
            downloaded[fname] = len(blob)
            print(f"  downloaded {fname:36s} {len(blob)/1024:6.1f} KB")
        # body already contains a full "@font-face { ... }" rule; just localize src.
        rule = body.replace(url, f"/fonts/vendor/{fname}").strip()
        out_rules.append(rule)

    header = ("/* Self-hosted fonts (latin subset). Generated by "
              "scripts/selfhost_fonts.py — do not edit by hand.\n"
              "   Replaces the runtime dependency on fonts.googleapis.com. */\n")
    with open(CSS_OUT, "w") as f:
        f.write(header + "\n".join(out_rules) + "\n")

    total = sum(downloaded.values())
    print(f"\n  {len(downloaded)} files, {total/1024:.1f} KB total -> {FONT_DIR}")
    print(f"  wrote {CSS_OUT}")


if __name__ == "__main__":
    sys.exit(main())
